// Pages exports
export { LandingPage as HomePage } from './public/HomePage';
export { AboutPage } from './public/AboutPage';
export { LoginPage } from './auth/LoginPage';
export { AdminLoginPage } from './auth/AdminLoginPage';
export { SetNewPasswordPage } from './auth/SetNewPasswordPage';
export { VerifyCertificatePage } from './public/VerifyCertificatePage';
export { default as StudentDashboard } from './student/StudentDashboard';
export { default as CoursesPage } from './student/Courses';
export { default as CalendarPage } from './student/Calendar';
export { default as AssignmentsPage } from './student/AssignmentsPage';
export { default as GradesPage } from './student/Grades';
export { ModulosPage } from './student/ModulosPage';
export { ModuloDetailPage } from './student/ModuloDetailPage';
export { CursoDetailPage } from './student/CursoDetailPage';
export { LessonPage } from './student/LessonPage';
export { QuizPage } from './student/QuizPage';
export { QuizResultPage } from './student/QuizResultPage';
export { ExamenFinalPage } from './student/ExamenFinalPage';
export { MyCoursesPage } from './student/MyCoursesPage';
export { ProgressPage } from './student/ProgressPage';
export { CertificatesPage } from './student/CertificatesPage';
export { ForumPage } from './student/ForumPage';
export { AdminDashboard } from './admin/AdminDashboard';
export { AdminUsersPage } from './admin/AdminUsersPage';
export { AdminCoursesPage } from './admin/AdminCoursesPage';
export { AdminReportsPage } from './admin/AdminReportsPage';
export { AdminSettingsPage } from './admin/AdminSettingsPage';
export { default as NotFoundPage } from './NotFoundPage';
